apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellodotnet5-deployement
spec:
  selector:
    matchLabels:
      app: hellodotnet5
  template:
    metadata:
      labels:
        app: hellodotnet5
    spec:
      containers:
        - name: hellodotnet5
          image: hellodotnet5:v1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          env:
            - name: MongoDbSettings__Host
              value: mongodb-service
            - name: MongoDbSettings__Password
              valueFrom:
                secretKeyRef:
                  name: hellodotnet5-secrets
                  key: mongodb-password
          livenessProbe:
            httpGet:
              path: /health/live
              port: 80
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: hellodotnet5-service
spec:
  type: LoadBalancer
  selector:
    app: hellodotnet5
  ports:
    - port: 80
      targetPort: 80
